name: openflexure-microscope-server
version: '2.5.0-beta.2-1'
summary: python test package
description: |
 test app for python
base: core18
confinement: strict
architectures:
  - build-on: arm64
    run-on: arm64
  - build-on: armhf
    run-on: armhf
  - build-on: amd64
    run-on: amd64

apps:
  run:
    command: python3 -m openflexure_microscope.api.app
    plugs:
      - home
      - mount-observe
      - serial-port
      - network
      - network-bind
      - opengl

parts:
  openflexure-microscope-server:
    plugin: python
    python-version: python3
    source: https://build.openflexure.org/openflexure-microscope-server/openflexure-microscope-server-v2.5.0-beta.2.tar.gz
    python-packages:
      # Upgrade pip and wheel
      - pip
      - wheel
    override-build: |
      # Let Python plugin set up environment
      snapcraftctl build
      # Add piwheels to pip indexes
      printf '[global]\nextra-index-url=https://www.piwheels.org/simple\n' > /etc/pip.conf
      # Install Poetry
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
      # Activate Poetry
      . $HOME/.poetry/env
      # Use default environment
      poetry config virtualenvs.create false
      # Install production
      poetry install --no-dev
      # Let Python plugin set up staging
      snapcraftctl build
    build-packages: [git, curl, findutils, zlib1g, python3-dev, python3-venv]
    build-environment:
      - C_INCLUDE_PATH: /usr/include/python3.6
    stage-packages: []
